// Generated by CoffeeScript 2.3.0
var CFX;

import {
  storiesOf
} from '@storybook/react';

import domWithLink from '../components/domWithLink';

import cfxify from 'cfx.react.dom';

CFX = cfxify({domWithLink});

export default function() {
  return storiesOf('domWithLink', module).add('domWithLink', () => {
    var c_domWithLink;
    ({c_domWithLink} = CFX);
    return c_domWithLink({});
  });
};
