// Generated by CoffeeScript 2.3.0
var CFX;

import {
  storiesOf
} from '@storybook/react';

import cfxify from 'cfx.react.dom';

import LinkTo from '../components';

import Link from './Link';

CFX = cfxify({
  toWelcome: LinkTo(Link)
});

export default function() {
  return storiesOf('Home', module).add('to Welcome', () => {
    var c_toWelcome;
    ({c_toWelcome} = CFX);
    return c_toWelcome({});
  });
};
