// Generated by CoffeeScript 2.3.0
import 'normalize.css/normalize.css';

import 'reset-css/reset.css';

import 'antd/dist/antd.min.css';

import Welcome from './Welcome';

import Home from './Home';

Welcome();

Home();
