// Generated by CoffeeScript 2.3.0
import {
  linkTo
} from '@storybook/addon-links';

import {
  // import LinkTo from '@storybook/addon-links/react'
  getLinks
} from 'cfx.react.link/dist/main';

export default getLinks({
  Welcome: ['Welcome', 'to Storybook']
}, {
  story: linkTo
});
