// Generated by CoffeeScript 2.3.0
var CFX;

import {
  storiesOf
} from '@storybook/react';

import test from '../components/test';

import cfxify from 'cfx.react.dom';

CFX = cfxify({test});

export default function() {
  return storiesOf('test', module).add('test', () => {
    var c_test;
    ({c_test} = CFX);
    return c_test({});
  });
};
