// Generated by CoffeeScript 2.3.0
var CFX;

import {
  storiesOf
} from '@storybook/react';

import {
  Welcome
} from '@storybook/react/demo';

import cfxify from 'cfx.react.dom';

CFX = cfxify({Welcome});

export default function() {
  return storiesOf('Welcome', module).add('to Storybook', () => {
    var c_Welcome;
    ({c_Welcome} = CFX);
    return c_Welcome({});
  });
};
