// Generated by CoffeeScript 2.3.0
var CFX;

import cfxify from 'cfx.react.dom';

import {
  domWithLink,
  getLinks
} from 'cfx.react.link.dom';

import Links from '../stories/Link';

import {
  Button
} from 'antd';

CFX = cfxify({'span': 'span', Button, domWithLink});

export default function() {
  var c_Button, c_domWithLink, c_span;
  ({c_span, c_Button, c_domWithLink} = CFX);
  return c_domWithLink({
    Link: getLinks({
      Link: Links,
      kind: 'Welcome'
    }),
    domObj: c_Button({
      type: 'primary'
    }, 'hello world!')
  });
};
