// Generated by CoffeeScript 2.3.1
var CFX;

import cfxify from 'cfx.react.dom';

import domWithLink from 'cfx.react.link.dom';

import Link from '../stories/Link';

import {
  Button
} from 'antd';

CFX = cfxify({'span': 'span', Button, domWithLink});

export default function() {
  var c_Button, c_domWithLink, c_span;
  ({c_span, c_Button, c_domWithLink} = CFX);
  return c_domWithLink({
    kind: 'Welcome',
    Link: Link,
    onClick: () => {
      return console.log('this is Links onClick!!!');
    },
    domObj: () => {
      return c_Button({
        type: 'primary'
      }, 'hello world!');
    }
  });
};
