// Generated by CoffeeScript 2.3.0
var CFX;

import cfxify from 'cfx.react.dom';

import getLinks from 'cfx.react.link/dist/main';

CFX = cfxify({'a': 'a'});

export default (Link) => {
  return () => {
    var c_Welcome;
    CFX = CFX._.extends(getLinks(Link, {
      Welcome: '/Welcome'
    }));
    ({c_Welcome} = CFX);
    return c_Welcome({}, 'Welcome');
  };
};
