// Generated by CoffeeScript 2.3.0
var CFX;

import cfxify from 'cfx.react.dom';

import {
  domWithLink,
  getLinks
} from 'cfx.react.link.dom';

import Links from '../stories/Link';

CFX = cfxify({'span': 'span', domWithLink});

export default function() {
  var c_domWithLink, c_span;
  ({c_span, c_domWithLink} = CFX);
  return c_domWithLink({
    DomObj: c_span({
      style: {
        color: 'red'
      }
    }, 'hello world!'),
    Link: getLinks({
      Link: Links,
      kind: 'Welcome'
    })
  });
};
